version: '2.1'

services:

  base-app:
    build:
      context: ${CODE_DIR}/connecting-to-services/
      args:
        NODE_ENV: ${NODE_ENV}
    command: yarn run watch-dev
    volumes:
      - ${CODE_DIR}/connecting-to-services/:/code
    environment:
      API_BASE_URL: 'http://nearby-services-api:3001'

  frontend:
    extends:
      service: base-app
    links:
      - nearby-services-api:nearby-services-api
    ports:
      - 3000:3000
    volumes:
      - c2s-node_modules:/code/node_modules

  nearby-services-api:
    build:
      context: ${CODE_DIR}/nearby-services-api/
      args:
        NODE_ENV: ${NODE_ENV}
    command: npm run watch-dev
    volumes:
      - ${CODE_DIR}/nearby-services-api/:/code
      - c2s-api-node_modules:/code/node_modules
    links:
      - pharmacy-db:mongo

  pharmacy-db:
    build:
      context: ${CODE_DIR}/docker-mongodb-pharmacy/
    ports:
      - 27017:27017

volumes:
  c2s-node_modules:
  c2s-api-node_modules: