version: '2.1'

services:

  tests:
    extends:
      file: docker-compose-c2s.yml
      service: base-app
    command: yarn run git-hook
    volumes:
      - c2s-tests-node_modules:/code/node_modules
    environment:
      NODE_ENV: test
    links:
      - nearby-services-api:nearby-services-api

  travis-tests:
    extends:
      file: docker-compose-c2s.yml
      service: base-app
    command: yarn run travis
    user: root
    volumes:
      - .:/code
      - c2s-travis-tests-node_modules:/code/node_modules
    environment:
      API_BASE_URL: 'http://nearby-services-api:3001'
      COVERALLS_REPO_TOKEN: ${COVERALLS_REPO_TOKEN}
      SNYK_TOKEN: ${SNYK_TOKEN}
      TRAVIS: ${TRAVIS}
      TRAVIS_BRANCH: ${TRAVIS_BRANCH}
      TRAVIS_COMMIT: ${TRAVIS_COMMIT}
      TRAVIS_JOB_ID: ${TRAVIS_JOB_ID}
    links:
      - nearby-services-api:nearby-services-api

  nearby-services-api:
    build:
      context: ${CODE_DIR}/nearby-services-api/
      args:
        NODE_ENV: development
    command: sh -c 'npm run git-hook && npm run snyk-test && npm run watch-test'
    environment:
      SNYK_TOKEN: ${SNYK_TOKEN}
      COVERALLS_REPO_TOKEN: ${COVERALLS_REPO_TOKEN}
    volumes:
      - ${CODE_DIR}/nearby-services-api/:/code
      - c2s-api-test-deps-node_modules:/code/node_modules
    links:
      - pharmacy-db:mongo

  pharmacy-db:
    build:
      context: ${CODE_DIR}/pharmacy-db/

volumes:
  c2s-tests-node_modules:
  c2s-travis-tests-node_modules:
  c2s-api-test-deps-node_modules:
    