# ./scripts/test-gp-finder
version: '2.1'

services:

  tests:
    extends:
      file: docker-compose-profiles.yml
      service: base-app
    command: sh -c "yarn run git-hook && yarn run test-watch"
    volumes:
      - profiles-tests-node_modules:/code/node_modules
    environment:
      NODE_ENV: test
    links:
      - profiles-db:mongo

  travis-tests:
    extends:
      file: docker-compose-profiles.yml
      service: base-app
    command:
      sh -c "npm run git-hook && npm run upload-coverage-coveralls"
    volumes:
      - profiles-travis-tests-node_modules:/code/node_modules
    environment:
      COVERALLS_REPO_TOKEN: ${COVERALLS_REPO_TOKEN}
      NODE_ENV: development
      SNYK_TOKEN: ${SNYK_TOKEN}
      TRAVIS: ${TRAVIS}
      TRAVIS_BRANCH: ${TRAVIS_BRANCH}
      TRAVIS_COMMIT: ${TRAVIS_COMMIT}
      TRAVIS_JOB_ID: ${TRAVIS_JOB_ID}
    links:
      - profiles-db:mongo

  profiles-db:
    build:
      context: ${CODE_DIR}/profiles-db/

volumes:
  profiles-tests-node_modules:
  profiles-travis-tests-node_modules:
