#!/bin/bash
# -p flag stands for --project-name and will create a different network for the test container
# so it won't interfere with the app container
docker-compose -p profiles-test-int -f docker-compose-profiles-tests.yml down -v
docker-compose -p profiles-test-int -f docker-compose-profiles-tests.yml up --build --force-recreate tests
